baseURL = "https://nhudait.github.io/"
languageCode = "en-us"
title = "Neha Hudait"
theme = "hugo-lodi-theme"
publishDir = "public"

[params]
    theme_color = "#3a7ca5"
    description = "Neha Hudait Personal Website"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "nehahudait@gmail.com"
    linkedin = "https://linkedin.com/in/nehahudait"
    github = "nhudait"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar2.png"
    subtitle = "Neha Hudait"
    hero_right = ["I'm a Security Product Manager based in San Francisco.","Currently, I am at NVIDIA building products and defining security strategy to make NVIDIA's and the industry's AI and accelerated computing products more secure." ,"When I'm not working, I love playing with my two kittens, Kaju and Kulfi, cooking new recipes, and playing mystery games on my Nintendo Switch."]

    resume = "resume.pdf"

[params.process]
    enable = false
    title = "Projects"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = false
    title = "Experience"
    subtitle = "Technical"

[params.projects]
    enable = false
    title = "Extracurriculars"
    subtitle = "Test"

[params.other]
    enable = true
    title = "Experience"
    subtitle = "Test"

[params.timeline]
    enable = true
    title = "Extracurriculars"
    subtitle = "Test"


[params.courses]
    enable = false
    title = "Courses"
    subtitle = "Test"

[params.footer]
    enable = true
