baseURL = "https://nhudait.github.io/"
languageCode = "en-us"
title = "Neha Hudait"
theme = "hugo-lodi-theme"
publishDir = "public"

[params]
    theme_color = "#3a7ca5"
    description = "Neha Hudait Personal Website"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "nhudait@berkeley.edu"
    linkedin = "https://linkedin.com/in/nehahudait"
    github = "nhudait"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi, I'm Neha, a recent UC Berkeley graduate passionate about making technology more accessible."
    hero_right = ["I recently graduated UC Berkeley with a dual-degree in [Electrical Engineering & Computer Sciences](https://eecs.berkeley.edu/) and [Business Administration](https://haas.berkeley.edu/) through the [Management, Entrepreneurship, and Technology](https://met.berkeley.edu) (M.E.T.) Program.",  " I'm from Southwest Virginia and am passionate about bridging the gap between technology and accessibility. I've seen the impact that technological gentrification and technological illteracy has on my community. As a result, I've dedicated much of my academic and professional career in exploring emerging technologies and how they can impact different use cases like my own community.", "I have experience in the fields of product and program management, software development, machine learning, and data analytics which you can read about below! I'm always looking for new and exciting opportunities! Feel free to shoot me an email at nhudait@berkeley.edu or [schedule a time to meet.](https://calendly.com/hudait)" ]

    resume = "resume.pdf"

[params.process]
    enable = true
    title = "Projects"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Experience"
    subtitle = "Technical"

[params.projects]
    enable = true
    title = "Extracurriculars"
    subtitle = "Test"

[params.other]
    enable = true
    title = "Additional"
    subtitle = "Test"

[params.courses]
    enable = false
    title = "Courses"
    subtitle = "Test"

[params.footer]
    enable = true
