name = "Hugo Lodi Theme"
license = "MIT"
licenselink = "https://github.com/xaviablaza/yourtheme/blob/master/LICENSE.md"
description = "Hugo Lodi Theme ported to Hugo by Xavi Ablaza"
homepage = "https://github.com/xaviablaza/hugo-lodi-theme"
tags = ["lodi", "responsive", "hero", "personal", "portfolio", "case study", "ux"]
features = ["homepage", "case studies", "process"]
min_version = "0.29"

[author]
  name = "Xavi Ablaza"
  homepage = "https://github.com/xaviablaza"

# If porting an existing theme
[original]
  author = "Alexis Collado"
  name = "Portfolio"
  homepage = "http://www.alexiscollado.com"
